name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.9'

    - name: Add conda to the system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name : Installing pip requirements
      run: |
          pip install --upgrade pip
          pip -r install requirements.txt

    - name : Setting up fake display
      run : |
            sudo apt-get update
            sudo apt-get -y install xvfb python3 python3-pip

    - name : Setup Xvfb
      run : 
          Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99

    - name : Install local Python enviroment
      run : pip3 install -e .

    - name : SOLO12_SIMULATION Test Script
      run: |
          python scripts/run.py
          

    

