name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10

    steps:

    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.9'

    - name: Add conda to the system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH


    - name : Setting up fake display
      run : |
            sudo apt-get update
            sudo apt-get -y install xvfb python3 python3-pip

    - name : Setup Xvfb
      run : 
          Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99

    - name: Install Eigen
      run: |
        sudo apt-get update
        sudo apt-get install libeigen3-dev

    - name : Installing Pinocchio 
      run  : |
          # git clone --recursive https://github.com/stack-of-tasks/pinocchio
          # cd pinocchio && mkdir build && cd build
          # git checkout master
          # cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          # make -j4
          # make install
          # sudo mkdir -p /etc/apt/keyrings 
          curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc
          sudo tee /etc/apt/keyrings/robotpkg.asc
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg"
          sudo tee /etc/apt/sources.list.d/robotpkg.list
          sudo apt-get update
          sudo apt install -qqy robotpkg-py3*-pinocchio
          export PATH=/opt/openrobots/bin:$PATH
          export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
          export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages:$PYTHONPATH # Adapt your desired python version here
          export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH


    - name : Installing pip requirements
      run: |
          pip install --upgrade pip
          pip install -r requirements.txt


    - name : Install local Python enviroment
      run : pip3 install -e .

    - name : QTOS test scripts for each navigation tasks
      run: |
          python scripts/main.py -T
          python scripts/main.py -T -exp exp_1
          python scripts/main.py -T -exp exp_3
          python scripts/main.py -T -exp exp_5

          

    

