name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:

    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.9'

    - name: Add conda to the system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name : Installing pip requirements
      run: |
          pip3 install --upgrade pip3
          pip3 install appnope==0.1.3
          pip3 install asttokens==2.2.1
          pip3 install backcall==0.2.0
          pip3 install backports.functools_lru_cache==1.6.4
          pip3 install certifi==2023.7.22
          pip3 install colorama==0.4.6
          pip3 install comm==0.1.2
          pip3 install contourpy==1.0.7
          pip3 install cycler==0.11.0
          pip3 install debugpy==1.6.6
          pip3 install decorator==5.1.1
          pip3 install dive==0.3
          pip3 install executing==1.2.0
          pip3 install fonttools==4.38.0
          pip3 install importlib_metadata==6.0.0
          pip3 install ipykernel==6.21.2
          pip3 install ipython==8.10.0
          pip3 install jedi==0.18.2
          pip3 install jupyter_client==8.0.2
          pip3 install jupyter_core==5.2.0
          pip3 install keyboard==0.13.5
          pip3 install kiwisolver==1.4.4
          pip3 install matplotlib==3.7.0
          pip3 install matplotlib_inline==0.1.6
          pip3 install munkres==1.1.4
          pip3 install nest_asyncio==1.5.6
          pip3 install numpy==1.24.2
          pip3 install packaging==23.0
          pip3 install pandas==2.0.1
          pip3 install parso==0.8.3
          pip3 install pexpect==4.8.0
          pip3 install pickleshare==0.7.5
          pip3 install Pillow==9.4.0
          pip3 install pinocchio==0.4.3
          pip3 install pip==23.0
          pip3 install platformdirs==3.0.0
          pip3 install prompt-toolkit==3.0.36
          pip3 install psutil==5.9.4
          pip3 install ptyprocess==0.7.0
          pip3 install pure-eval==0.2.2
          pip3 install pybullet==3.2.0
          pip3 install Pygments==2.14.0
          pip3 install pyparsing==3.0.9
          pip3 install python-dateutil==2.8.2
          pip3 install pytz==2023.3
          pip3 install PyYAML==6.0
          pip3 install pyzmq==25.0.0
          pip3 install scipy==1.10.1
          pip3 install setuptools==67.3.1
          pip3 install six==1.16.0
          pip3 install stack-data==0.6.2
          pip3 install tornado==6.2
          pip3 install traitlets==5.9.0
          pip3 install typing_extensions==4.4.0
          pip3 install tzdata==2023.3
          pip3 install unicodedata2==15.0.0
          pip3 install wcwidth==0.2.6
          pip3 install wheel==0.38.4
          pip3 install zipp==3.13.0

    - name : Setting up fake display
      run : |
            sudo apt-get update
            sudo apt-get -y install xvfb python3 python3-pip

    - name : Setup Xvfb
      run : 
          Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99

    - name : Install local Python enviroment
      run : pip3 install -e .

    - name : SOLO12_SIMULATION Test Script
      run: |
          python scripts/run.py
          

    

