name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.9'
    - name: Add conda to the system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Setting up Conda enviroment
      run: |
        conda create -n soloSIM python=3.10 -y
        conda init bash
        source $HOME/.bashrc
        conda activate soloSIM

    - name : Installing pip requirements
      run: |
          pip3 install -r requirements.txt

    - name : Setting up fake display
      run : |
            sudo apt-get update
            sudo apt-get -y install xvfb python3 python3-pip

    - name : Setup Xvfb
      run : 
          Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99

    - name : SOLO12_SIMULATION Script Tests
      run: |
          python scripts/run.py
          

    

